services:
  app:
    build: ./app/
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=123L123
      - DB_NAME=database
    ports:
      - "5001:5001"
    networks:
      - m_an_network

  db:
    build: ./database/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123L123
      - POSTGRES_DB=database
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - m_an_network

networks:
  m_an_network:
    driver: bridge
